apiVersion: v1
kind: Pod
metadata:
  name: hello-world-wasmcloud-assemblyscript
spec:
  containers:
    - name: hello-world-wasmcloud-assemblyscript
      image: webassembly.azurecr.io/hello-world-wascc-assemblyscript:v0.1.0
      ports:
        - containerPort: 8080
          hostPort: 8080
  nodeSelector:
    beta.kubernetes.io/arch: wasm32-wasmcloud
  tolerations:
    - key: "node.kubernetes.io/network-unavailable"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasmcloud"
      effect: "NoExecute"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasmcloud"
      effect: "NoSchedule"
