apiVersion: v1
kind: Pod
metadata:
  name: uppercase
  labels:
    app: uppercase
spec:
  containers:
    - image: webassembly.azurecr.io/uppercase-wascc:v0.3
      imagePullPolicy: Always
      name: uppercase
      ports:
        - containerPort: 8080
          hostPort: 8080
  nodeSelector:
    beta.kubernetes.io/os: linux
    beta.kubernetes.io/arch: wasm32-wasmcloud
  tolerations:
    - key: "node.kubernetes.io/network-unavailable"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasmcloud"
      effect: "NoExecute"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasmcloud"
      effect: "NoSchedule"
