name: release
on:
  push:
    branches:
      - master
    tags:
      - "v*"
jobs:
  build_and_publish:
    name: build release assets
    runs-on: ${{ matrix.config.os }}
    env: ${{ matrix.config.env }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: "ubuntu-latest",
              arch: "amd64",
              args: "--release",
              targetDir: "target/release",
              extension: "",
              env: {},
            }
          - {
              os: "ubuntu-latest",
              arch: "aarch64",
              args: "--release --target aarch64-unknown-linux-gnu",
              targetDir: "target/aarch64-unknown-linux-gnu/release",
              extension: "",
              env: { OPENSSL_DIR: "/usr/local/openssl-aarch64" },
            }
          - {
              os: "macos-latest",
              arch: "amd64",
              args: "--release",
              targetDir: "target/release",
              extension: "",
              env: {},
            }
          - {
              os: "windows-latest",
              arch: "amd64",
              args: "--release --no-default-features --features rustls-tls",
              targetDir: "target/release",
              extension: ".exe",
              env: {},
            }
    steps:
      - uses: actions/checkout@v2

      - name: set the release version (tag)
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: set the release version (master)
        if: github.ref == 'refs/heads/master'
        shell: bash
        run: echo "RELEASE_VERSION=canary" >> $GITHUB_ENV

      - name: lowercase the runner OS name
        shell: bash
        run: |
          OS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
          echo "RUNNER_OS=${OS}" >> $GITHUB_ENV

      # hack(bacongobbler): install rustfmt to work around darwin toolchain issues
      - name: "(macOS) install dev tools"
        if: runner.os == 'macOS'
        run: |
          rustup component add rustfmt --toolchain stable-x86_64-apple-darwin
          rustup component add clippy --toolchain stable-x86_64-apple-darwin
          rustup update stable

      - name: setup for cross-compile builds
        if: matrix.config.arch == 'aarch64'
        run: |
          sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          cd /tmp
          git clone https://github.com/openssl/openssl
          cd openssl
          git checkout OpenSSL_1_1_1h
          sudo mkdir -p $OPENSSL_DIR
          ./Configure linux-aarch64 --prefix=$OPENSSL_DIR --openssldir=$OPENSSL_DIR shared
          make CC=aarch64-linux-gnu-gcc
          sudo make install
          rustup target add aarch64-unknown-linux-gnu

      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.config.args }}

      - name: package release assets
        shell: bash
        run: |
          mkdir _dist
          cp README.md LICENSE ${{ matrix.config.targetDir }}/krustlet-wasmcloud${{ matrix.config.extension }} _dist/
          cd _dist
          tar czf krustlet-wasmcloud-${{ env.RELEASE_VERSION }}-${{ env.RUNNER_OS }}-${{ matrix.config.arch }}.tar.gz README.md LICENSE krustlet-wasmcloud${{ matrix.config.extension }}

      - name: calculate checksum (all except macOS)
        shell: bash
        if: runner.os != 'macOS'
        run: sha256sum _dist/krustlet-wasmcloud-${{ env.RELEASE_VERSION }}-${{ env.RUNNER_OS }}-${{ matrix.config.arch }}.tar.gz > _dist/checksum-${{ env.RELEASE_VERSION }}-${{ env.RUNNER_OS }}-${{ matrix.config.arch }}.txt

      - name: calculate checksum (macOS)
        shell: bash
        if: runner.os == 'macOS'
        run: shasum -a 256 _dist/krustlet-wasmcloud-${{ env.RELEASE_VERSION }}-${{ env.RUNNER_OS }}-${{ matrix.config.arch }}.tar.gz > _dist/checksum-${{ env.RELEASE_VERSION }}-${{ env.RUNNER_OS }}-${{ matrix.config.arch }}.txt

      - name: Upload tarball
        uses: actions/upload-artifact@v1
        with:
          name: krustlet-wasmcloud
          path: _dist/krustlet-wasmcloud-${{ env.RELEASE_VERSION }}-${{ env.RUNNER_OS }}-${{ matrix.config.arch }}.tar.gz
      - name: Upload checksum
        uses: actions/upload-artifact@v1
        with:
          name: krustlet-wasmcloud
          path: _dist/checksum-${{ env.RELEASE_VERSION }}-${{ env.RUNNER_OS }}-${{ matrix.config.arch }}.txt
